site_description: "XLua"
github: https://github.com/Tencent/xLua
modify_github: https://github.com/Tencent/xLua/tree/master/docs/src/
copyright: © Copyright 2017 Ourpalm All Rights Reserved
copyright_desc: Tencent2017